"""add total amount

Revision ID: 39856d58e5ea
Revises: b02ff6c4ab64
Create Date: 2026-08-25 22:34:48.688918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39856d58e5ea'
down_revision: Union[str, Sequence[str], None] = 'b02ff6c4ab64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('total_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_amount')
    # ### end Alembic commands ###
